spring:
  profiles:
    active: local
  application:
    name: ruogu-ai-agent
server:
  servlet:
    context-path: /api

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ruogu.agent.controller

# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
